In [17]:
import numpy as np
import pandas as pd

In [45]:
result = np.array([[2,2,3,1],
                  [9,8,10,9],
                  [8,3,2,7],
                  [7,1,3,8],
                  [2,9,8,2],
                  [5,4,5,5]])

In [103]:
a_mean = np.sum(result, axis = 0) / result.shape[0]  # 列ごとに集計 -> 各教科の点数合計
b_mean =  np.sum(result, axis = 1) / result.shape[1] # 行ごとに集計 -> 各個人の点数合計
((result - a_mean)**2) / result.shape[0]  # 　分散行列

array([[2.04166667, 1.04166667, 0.78240741, 3.12962963],
       [2.04166667, 2.04166667, 3.89351852, 2.24074074],
       [1.04166667, 0.375     , 1.6712963 , 0.46296296],
       [0.375     , 2.04166667, 0.78240741, 1.18518519],
       [2.04166667, 3.375     , 1.33796296, 1.85185185],
       [0.04166667, 0.04166667, 0.00462963, 0.01851852]])

In [105]:
centerling = result - a_mean  # 中心化

In [82]:
np.sum((result - a_mean)**2, axis = 0) / 5

array([ 9.1       , 10.7       , 10.16666667, 10.66666667])

In [84]:
# 分散共分散行列を求める
cov_mat =  np.cov(result.T)
cov_mat

array([[ 9.1       , -0.7       ,  0.7       ,  9.6       ],
       [-0.7       , 10.7       ,  9.5       , -0.6       ],
       [ 0.7       ,  9.5       , 10.16666667,  1.33333333],
       [ 9.6       , -0.6       ,  1.33333333, 10.66666667]])

In [87]:
# 固有値を求める
linagl = np.linalg.eig(cov_mat) # 固有値に対応する固有ベクトルは縦ベクトル
linagl[1]

array([[-0.5640232 , -0.37027138,  0.67756299,  0.29272055],
       [ 0.4568188 , -0.5572669 , -0.20977689,  0.6608811 ],
       [ 0.34009101, -0.61056538,  0.24044969, -0.67359629],
       [-0.59794022, -0.42374829, -0.66263564, -0.15433367]])

In [107]:
# 主成分得点を求める -> 例：１人目の第一主成分得点
(linagl[1][:,1]) @ centerling[0].T

5.848251353667354

In [108]:
a_mean

array([5.5       , 4.5       , 5.16666667, 5.33333333])

In [109]:
centerling

array([[-3.5       , -2.5       , -2.16666667, -4.33333333],
       [ 3.5       ,  3.5       ,  4.83333333,  3.66666667],
       [ 2.5       , -1.5       , -3.16666667,  1.66666667],
       [ 1.5       , -3.5       , -2.16666667,  2.66666667],
       [-3.5       ,  4.5       ,  2.83333333, -3.33333333],
       [-0.5       , -0.5       , -0.16666667, -0.33333333]])